### ISSUE TITLE
Missing some icons!

### ISSUE THREAD

**Issue by Sun8ox** [kuroehanako/OneUI4-Icons#1]
I have Debian 11 and Xfce4.16 and for unknown reasons I miss quite important icons. E.g. Bluetooth, Wifi, Remote Folder...
I don't know what else to write about it.

![Screenshot_2022-01-29_20-25-21](https://user-images.githubusercontent.com/65650506/151674867-0640f972-da2f-42d1-9b5a-db9389ae9c6b.png)

**Comment by Sun8ox** [comment]
I know it's not much but I would love for all those icons to work

**Comment by Sun8ox** [comment]
I fixed this by moving a few missing icons from the Infinity Star / Dream icons.

**Comment by Sun8ox** [comment]
Icons are probably missing. I copied more than 100 icons from that Infinity Dream and it works, but I think you should fix it. Unfortunately, I don't know exactly what the icons were, but everything works for me (now).

**Comment by Sun8ox** [comment]
![Screenshot_2022-01-29_22-15-50](https://user-images.githubusercontent.com/65650506/151677776-4a9fdf31-4e1c-4beb-815e-417a1f786d20.png)

**Comment by mjkim0727** [comment]
I'll add missing icons if I'm not busy. Also, I'm busy for classes and updates will be delayed too much.
